### ISSUE TITLE
iOS build failing with version 2.0.5

### ISSUE THREAD

**Issue by nihalreddy33** [deepak786/intercom_flutter#38]
After updating the plugin to the latest version (2.0.5) we are facing issues while building the iOS APP on XCODE 10. The version 2.0.4 was working fine before the new update, now even after changing the version to 2.0.4 it's failing to build.

**Below is the Exception that we are getting.**

Launching lib/main.dart on iPhone Xʀ in debug mode...
Xcode build done.                                           15.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Undefined symbols for architecture x86_64:
      "_UISceneWillEnterForegroundNotification", referenced from:
          +[ICMBridge load] in Intercom(ICMBridge.o)
      "___isPlatformVersionAtLeast", referenced from:
          -[IntercomSDK_IntercomConversationCollectionViewController insetsForAccessoryView] in Intercom(IntercomConversationCollectionViewController.o)
          +[IntercomSDK_ITBUpload createUploadForMediaAsset:completion:] in Intercom(ITBUpload.o)
          +[IntercomSDK_ITBUpload processImageDataForUpload:mediaAsset:info:imageUploadDataUTI:completion:] in Intercom(ITBUpload.o)
          -[IntercomSDK_IIMInputAccessoryView createConstraints] in Intercom(IIMInputAccessoryView.o)
          -[IntercomSDK_IIMInputButtonContainerView createConstraints] in Intercom(IIMInputButtonContainerView.o)
          -[IntercomSDK_IIMMediaViewController updateCollectionViewContentInsets] in Intercom(IIMMediaViewController.o)
          -[IntercomSDK_IIMMediaViewController layoutExpandButton] in Intercom(IIMMediaViewController.o)
          ...
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
Could not build the application for the simulator.
Error launching application on iPhone Xʀ.

**Flutter Doctor**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.7-pre.13, on Mac OS X 10.14.6 18G95, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[!] Android Studio (version 2.3)
    ✗ Flutter plugin version 12.1 - the recommended minimum version is 16.0.0
[!] IntelliJ IDEA Ultimate Edition (version 2016.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ This install is older than the minimum recommended version of 2017.1.0.
[!] IntelliJ IDEA Community Edition (version 2017.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.38.1)
[✓] Connected device (3 available)

@Zazo032 I have created a new issue to track this.

**Comment by Zazo032** [comment]
This may be solved by https://github.com/v3rm0n/intercom_flutter/commit/1dc21162e07220eb809b4aadbad314a1c42f2497

Maybe a 2.0.5+1 release to pub with this commit will fix the issue? @v3rm0n

**Comment by v3rm0n** [comment]
Let's see, 2.5.0+1 is published.

**Comment by anttka4** [comment]
Hi! Updating to 2.0.5+1 didn't resolve the issue:

15:21:29.887 12 info flutter.tools Xcode's output:
15:21:29.887 13 info flutter.tools ↳
15:21:29.887 14 info flutter.tools     warning: The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target. (in target 'Runner')
15:21:29.887 15 info flutter.tools     error: the following command failed with exit code 0 but produced no further output
15:21:29.887 16 info flutter.tools     CompileC /Library/Developer/Xcode/DerivedData/Runner-fhvdjznujykmhmfimcqstwgcaxvx/Build/Intermediates.noindex/Pods.build/Debug-
15:21:29.887 17 info flutter.tools     7 warnings generated.
15:21:29.887 18 info flutter.tools     7 warnings generated.
15:21:29.887 19 info flutter.tools     2 warnings generated.
15:21:29.887 20 info flutter.tools     s generated.
15:21:29.887 21 info flutter.tools     Undefined symbols for architecture x86_64:
15:21:29.887 22 info flutter.tools       "_UISceneWillEnterForegroundNotification", referenced from:
15:21:29.887 23 info flutter.tools           +[ICMBridge load] in Intercom(ICMBridge.o)
15:21:29.887 24 info flutter.tools       "___isPlatformVersionAtLeast", referenced from:
15:21:29.887 25 info flutter.tools           -[IntercomSDK_IntercomConversationCollectionViewController insetsForAccessoryView] in Intercom(IntercomConversationCollectionViewController.o)
15:21:29.887 26 info flutter.tools           +[IntercomSDK_ITBUpload createUploadForMediaAsset:completion:] in Intercom(ITBUpload.o)
15:21:29.887 27 info flutter.tools           +[IntercomSDK_ITBUpload processImageDataForUpload:mediaAsset:info:imageUploadDataUTI:completion:] in Intercom(ITBUpload.o)
15:21:29.887 28 info flutter.tools           -[IntercomSDK_IIMInputAccessoryView createConstraints] in Intercom(IIMInputAccessoryView.o)
15:21:29.887 29 info flutter.tools           -[IntercomSDK_IIMInputButtonContainerView createConstraints] in Intercom(IIMInputButtonContainerView.o)
15:21:29.888 30 info flutter.tools           -[IntercomSDK_IIMMediaViewController updateCollectionViewContentInsets] in Intercom(IIMMediaViewController.o)
15:21:29.888 31 info flutter.tools           -[IntercomSDK_IIMMediaViewController layoutExpandButton] in Intercom(IIMMediaViewController.o)
15:21:29.888 32 info flutter.tools           ...
15:21:29.888 33 info flutter.tools     ld: symbol(s) not found for architecture x86_64
15:21:29.888 34 info flutter.tools     clang: error: linker command failed with exit code 1 (use -v to see invocation)
15:21:29.888 35 info flutter.tools     note: Using new build systemnote: Planning buildnote: Constructing build description

**Comment by ciceropablo** [comment]
@anttka4 (@nihalreddy33 @Zazo032  @v3rm0n), really it's not resolve the problem. 😞

**Comment by nihalreddy33** [comment]
@Zazo032 it's not working with the new 2.0.5+1 release as well. We are getting the same exception.

**Comment by Zazo032** [comment]
Just updated my mac to latest Catalina beta and Xcode 11, and the errors are gone. I'll open a PR with the project changes, try that version and provide feedback to check if that works, please. Also, upgrade to latest Xcode version (not sure if macOS 10.15 Catalina is mandatory).

**Comment by Zazo032** [comment]
Just as a side note, try running `flutter clean`, also navigate to your `ios/` directory and run `pod update`. Lastly, try using the Flutter master branch. This worked for me.

**Comment by Zazo032** [comment]
Also, in your app's `main` method, add `WidgetsFlutterBinding.ensureInitialized();` on the first line.

**Comment by Zazo032** [comment]
When https://github.com/v3rm0n/intercom_flutter/pull/39 is merged, it'll be pushed to pub.dev so you can try if it works.

**Comment by nihalreddy33** [comment]
@Zazo032 I have tried all the steps that you told, but it's not working, are running your project on XCODE 10 or XCODE 11?

**Comment by Zazo032** [comment]
Xcode 11, try using latest version (`2.0.5+2`)

**Comment by nihalreddy33** [comment]
@Zazo032 will the (2.0.5+2) work on Xcode10?

**Comment by Zazo032** [comment]
I bumped the project to be Xcode 11 compatible (not sure if required) because that's the only way I could compile to an iOS 13 simulator withoud build errors
