### ISSUE TITLE
iOS build issue with latest version of flutter (V 1.22.0)

### ISSUE THREAD

**Issue by anilslabs** [deepak786/intercom_flutter#94]
**Flutter doctor:** 
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.3 19D76, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.49.3)
[✓] Connected device (1 available)`
 
(Issue while running on  both simulator and physical device)

**Issue:**

Undefined symbols for architecture arm64:

      "_OBJC_CLASS_$_UIPointerStyle", referenced from:
        objc-class-ref in Intercom(ICMPointerInteraction.o)
      "_OBJC_CLASS_$_UIPointerLiftEffect", referenced from:
         objc-class-ref in Intercom(ICMPointerInteraction.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

I tried replicating the issue with the example provided with the plugin also, but facing the same issue in iOS.

**Not able to run the provided example**

**Comment by ccfiel** [comment]
Is this already fix? 😊

**Comment by akanksha820** [comment]
**issue:**
Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_UIPointerStyle", referenced from:
          objc-class-ref in Intercom(ICMPointerInteraction.o)
      "_OBJC_CLASS_$_UIPointerLiftEffect", referenced from:
          objc-class-ref in Intercom(ICMPointerInteraction.o)
    ld: symbol(s) not found for architecture x86_64
    
   Any fix for this? My app works fine on lower version where **Intercom is 6.0.2** but not when it points to **7.1.0**
   If i downgrade the version, i wont be able to get the push notifications for IOS in place 
   
  Waiting on this fix badly @v3rm0n

**Comment by v3rm0n** [comment]
Hey, sorry I don’t even have Flutter on my computer so I’m not going to do any fixes, but I’m willing to accept tested PR’s 🙂

**Comment by akanksha820** [comment]
Hey, got it working in xcode 11.7. The app now builds as expected
Flutter version : 1.12.13+hotfix.7
Thanks  @v3rm0n

**Comment by deepak786** [comment]
closing this. Feel free to create a new one, if the issue still persists.
