### ISSUE TITLE
Android build crashes after upgrading to Intercom 9.0.5/9.0.6.

### ISSUE THREAD

**Issue by florinleu** [deepak786/intercom_flutter#439]
**Environment:**
Flutter 3.19.6/3.22.1
Intercom 9.0.5/9.0.6
VSCode 1.89.1
MacOS 14.5

When trying to build a release for Android I get the following error:
ERROR:/Users/builder/.gradle/caches/transforms-3/281d4165655ea893dd7147c4b25ba565/transformed/vectordrawable-animated-1.2.0-runtime.jar: R8: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null

A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable Compilation failed to complete, origin: /Users/builder/.gradle/caches/transforms-3/281d4165655ea893dd7147c4b25ba565/transformed/vectordrawable-animated-1.2.0-runtime.jar:androidx/vectordrawable/graphics/drawable/Animatable2Compat$AnimationCallback$1.class

**Comment by GabriellArthur** [comment]
I have the same problem.

**Comment by GabriellArthur** [comment]
Using bitrise to generate apk, it gives me this error:

```
ERROR:/Users/vagrant/.gradle/caches/transforms-3/81e565530d36f060670936a0807a9373/transformed/vectordrawable-animated-1.2.0-runtime.jar: R8: java.lang.NullPointerException
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:minifyDevReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete, origin: /Users/vagrant/.gradle/caches/transforms-3/81e565530d36f060670936a0807a9373/transformed/vectordrawable-animated-1.2.0-runtime.jar:androidx/vectordrawable/graphics/drawable/Animatable2Compat$AnimationCallback$1.class
```
   
A workaround to continue building. app and not stop development was to fix the intercom version at 9.0.0

```
intercom_flutter: 9.0.0
```

**Comment by deepak786** [comment]
Looks like the same issue https://github.com/v3rm0n/intercom_flutter/issues/436

Can you please try updating your Gradle version same as the example app? https://github.com/v3rm0n/intercom_flutter/issues/436#issuecomment-2146614948

**Comment by daniloapr** [comment]
Same here. I'm using the version 9.0.4 as recommended [here](https://github.com/flutter/flutter/issues/149798)

**Comment by greatschism** [comment]
Do any of you have it working with Flutter >3.19

**Comment by lucasfariasv** [comment]
I'm using Flutter 3.22.2 and intercom_flutter 9.0.7, I updated the version of gradle and kotlin and it worked, just as described [here](https://github.com/v3rm0n/intercom_flutter/issues/436#issuecomment-2146614948) and [here](https://github.com/v3rm0n/intercom_flutter/issues/436#issuecomment-2149153336)

**Comment by deepak786** [comment]
Duplicate of https://github.com/v3rm0n/intercom_flutter/issues/436

**Comment by deepak786** [comment]
You need to use AGP version 8. Please follow the below steps:

- android/app/build.gradle
Make sure to add the following under android section
```
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
```

- android/gradle/wrapper/gradle-wrapper.properties
Update your distributionUrl
```
distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-bin.zip
```

- android/settings.gradle
```
id "com.android.application" version "8.1.4" apply false
id "org.jetbrains.kotlin.android" version "1.9.21" apply false
```

For ref see this commit: https://github.com/v3rm0n/intercom_flutter/commit/6cd517bf146b88e49e22b4ebe9588dcdce02e918
