### ISSUE TITLE
Version 5.1.0 build errors

### ISSUE THREAD

**Issue by joknjokn** [deepak786/intercom_flutter#181]
Hi,

I'm trying to upgrade to the new 5.1.0, but I get a bunch of build errors, i.e.:
\intercom_flutter-5.1.0\android\src\main\java\io\maido\intercom\PushInterceptService.java:7: error: package com.google.firebase.messaging does not exist
import com.google.firebase.messaging.FirebaseMessagingService;

Do we need to change/upgrade anything else for this version?

**Comment by deepak786** [comment]
@joknjokn thank you for reporting this issue. I can also reproduce it at my end.

**Comment by michael-monta** [comment]
deepak786, than you for looking into it - do you have a rough estimate on when it's expected to be ready? :)

**Comment by michael-monta** [comment]
If it could be done asap it would be highly appreciated

**Comment by joknjokn** [comment]
Would it make sense to try with 10.2.0 and release that if it works, then work on 10.4.0/10.3.0 afterwards?

**Comment by michael-monta** [comment]
That would be good yes

**Comment by deepak786** [comment]
use updated version `intercom_flutter: 5.1.0+1`

And don't hesitate to buy me a coffee https://www.buymeacoffee.com/deepakdroid :)

**Comment by joknjokn** [comment]
It works. Thank you!
